### ISSUE TITLE
this input causes the entire virtual memory to be executed as a program

### ISSUE THREAD

**Issue by sohpeach** [lucas-streanga/Processor-Project#1]
```
0!
```

just a fun quirk i noticed in your parser

i guess this is actually intended? well, i enjoyed messing with it anyway

**Comment by lucas-streanga** [comment]
This is actually intentional haha. The PC just goes through all the memory and executes it. The goal was to emulate a real program loaded into memory. The memory is zero'd out and if no instructions are placed it'll just execute 0's until the PC reaches the end of memory.
